@extends('layouts.page')

@section('title', '利用規約')
@section('description', '利用規約のページです。バイク・車好きのためのウェブアプリ「モタサポ」の公式アプリです。')
@section('pageCss')
@section('h1', '利用規約')
@endsection

@include('layouts.header')
@section('content')
<div class="page-text page-content">
    <h2>利用規約</h2>
    <ol>
        <li>利用規約</li>
        <li>利用規約</li>
        <ol>
            <li>利用規約</li>
            <li>利用規約</li>
        </ol>
        <li>利用規約</li>
        <li>利用規約</li>
        <li>利用規約</li>
        <li>利用規約</li>
    </ol>
    <h2>利用規約</h2>
    <p>利用規約利用規約利用規約利用規約利用規約利用規約利用規約利用規約利用規約利用規約利用規約利用規約</p>
    <ol>
        <li>利用規約</li>
        <li>利用規約
            <ol>
                <li>利用規約</li>
                <li>利用規約
                    <ol>
                        <li>利用規約</li>
                        <li>利用規約</li>
                    </ol>
                </li>
            </ol>
        </li>
        <li>利用規約</li>
        <li>利用規約
            <ol>
                <li>利用規約</li>
                <li>利用規約
                    <ol>
                        <li>利用規約</li>
                        <li>利用規約</li>
                    </ol>
                </li>
            </ol>
        </li>
        <li>利用規約</li>
        <li>利用規約</li>
    </ul>
    <h2>利用規約</h2>
    <ol>
        <li>利用規約</li>
        <li>利用規約
            <ol>
                <li>利用規約</li>
                <li>利用規約
                    <ol>
                        <li>利用規約</li>
                        <li>利用規約</li>
                    </ol>
                </li>
            </ol>
        </li>
        <li>利用規約</li>
        <li>利用規約
            <ol>
                <li>利用規約</li>
                <li>利用規約
                    <ol>
                        <li>利用規約</li>
                        <li>利用規約</li>
                    </ol>
                </li>
            </ol>
        </li>
        <li>利用規約</li>
        <li>利用規約</li>
    </ol>
</div>
@endsection
@include('layouts.footer')
